### ISSUE TITLE
Invalid SchemaBuilder call: default has already been set.

### ISSUE THREAD

**Issue by bazoonchik** [oryanmoshe/debezium-timestamp-converter#6]
Upon creating a mysql connector with the following config settings like in your readme sample, the timestampConverter converter causes the following exception and prevents the connector to start.

org.apache.kafka.connect.errors.ConnectException: Invalid SchemaBuilder call: default has already been set.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid SchemaBuilder call: default has already been set.
	at org.apache.kafka.connect.data.SchemaBuilder.checkCanSet(SchemaBuilder.java:437)
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:126)
	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:380)
	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:119)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:117)
	at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)
	at io.debezium.connector.mysql.MySqlSchema.lambda$applyDdl$5(MySqlSchema.java:392)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.debezium.connector.mysql.MySqlSchema.applyDdl(MySqlSchema.java:386)
	at io.debezium.connector.mysql.SnapshotReader.lambda$readTableSchema$15(SnapshotReader.java:866)
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:537)
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:478)
	at io.debezium.connector.mysql.SnapshotReader.readTableSchema(SnapshotReader.java:864)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:526)

**Comment by bsshin71** [comment]
I also met the same error , when timestamp column has a default value.

**Comment by adisheshkishore** [comment]
Yes this happens even for me. I am going to attempt a fix on this today.

**Comment by adisheshkishore** [comment]
I was able to fix this for my use case. You can add the following to the timetamp converter file at line number 99,

if(millis == 0L){
                    log.info("[TimestampConverter.converterFor] returning default null values as null");
                    return null;
                }

**Comment by bugcai** [comment]
> @bsshin71 I was able to fix this for my use case. You can add the following to the timetamp converter file at line number 99,
> 
> if(millis == 0L){
> return null;
> }

Code at Line number 99 is as follows:
`    private Long getMillis(String timestamp, boolean isTime) {`

Are you sure to add here?

**Comment by Alonreznik** [comment]
I think there's a need just to return the `column.defaultValue()` if default value option exists.
